import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '../components/Cabecalho.jsx'
import Rodape from '../components/Rodape.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inova-X',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>

        <Cabecalho/>
        {children}
        <Rodape/>

      </body>
    </html>
  )
}
